### PR TITLE
Adding Courier Grid Data Resolver for LeBlender controls

### PR DESCRIPTION
**Pull request by hfloyd**
Requires version 2.52.4+ of Courier to function. (DLLs included in /Courier/Dependencies/ folder due to there not being a nuget package available (see: https://our.umbraco.org/forum/umbraco-pro/courier/64035-Courier-Nuget-Package)

https://our.umbraco.org/projects/umbraco-pro/umbraco-courier-2/

### CODE REVIEW

**Comment by danimalx** [comment]
Installed data resolver but it throws errors on target server:

2016-05-05 06:39:24,757 [130] ERROR Lecoati.LeBlender.Extension.Courier.LeBlenderGridDataResolver - [Thread 278] NON-CRITICAL: LeBlenderGridDataResolver.ShouldRun had an error
System.NullReferenceException: Object reference not set to an instance of an object.
   at Lecoati.LeBlender.Extension.Courier.LeBlenderGridDataResolver.ShouldRun(String view, GridValueControlModel cell)
2016-05-05 06:39:24,757 [130] ERROR Lecoati.LeBlender.Extension.Courier.LeBlenderGridDataResolver - [Thread 278] NON-CRITICAL: LeBlenderGridDataResolver.ShouldRun had an error
System.NullReferenceException: Object reference not set to an instance of an object.
   at Lecoati.LeBlender.Extension.Courier.LeBlenderGridDataResolver.ShouldRun(String view, GridValueControlModel cell)

**Comment by hfloyd** [comment]
Hi @danimalx, Yes, "ShouldRun" sometimes errors because it gets called frequently by Courier - but it isn't always important -  that is why I marked the error message as "NON-CRITICAL" in the log, so it's more an FYI.

Are you having issues with the functionality (aka - It doesn't work)?

**Comment by danimalx** [comment]
That's correct it doesn't work. Nothing is transferred.

**Comment by hfloyd** [comment]
And you have Courier version 2.52.4+ installed in your site, and have a valid license file installed?

Where are you encountering the error - when you go to the "Deployments" tab on Content?

Also, have you tried setting a breakpoint to determine WHAT exactly is null? 

I've had success with this on both "regular" Courier sites as well as UaaS sites requiring the "Concorde" version of Courier.

**Comment by danimalx** [comment]
And you have Courier version 2.52.4+ installed in your site, and have a valid license file installed? **Yes the latest version and a valid license.

Where are you encountering the error - when you go to the "Deployments" tab on Content? **There is no error on the screen, it fails silently. I found the error above in the log.

Also, have you tried setting a breakpoint to determine WHAT exactly is null? **Where would I set this breakpoint? In your data resolver?

I've had success with this on both "regular" Courier sites as well as UaaS sites requiring the "Concorde" version of Courier.

**Comment by hfloyd** [comment]
RE: the error - you see the error appear in the log after using the "Deployments" "Transfer Queue" button?

Regarding the Content node you are transferring, I assume it has a LeBlender grid control on it? Does it reference a media item? If so, does the packager locate the media item for transfer along with the content?

Also, keep in mind that this DataResolver basically passes individual properties to their own Data Resolvers - so if you have non-standard DataTypes in your custom LeBlender editor which don't have their own resolvers installed, (like NestedContent or Archetype or whatever), that could cause a problem as well.

Yes, set the breakpoint in my Data Resolver file at the beginning of the "ShouldRun" function.

**Comment by richieallen** [comment]
Hey guys,

Are you any closer to getting this merged in and included in a release of LeBlender?

Many thanks

Rich

**Comment by hfloyd** [comment]
@danimalx Does my recent update help your issue?  Also, please check the CourierLog.txt file if you are seeing error messages. If the error happens before deploying (on packaging) check the source website's CourierLog, and if it happens after clicking the "Deploy" button, (on extracting) then check the CourierLog on the destination website.

@richieallen : You'll have to take that up with the Lecoati guys :-)

**Comment by mattmorrisonsolidstudios** [comment]
Hey hfloyd,

Thanks for your efforts on this. I updated it though making use of c# 6, dynamic objects and abstracted some logic to their own functions; I tried to use SOLID to enhance your code and also removed all the string building which was prone to errors in nested scenarios. As JObjects, JArrays and JTokens are used in the plugin, I have also made use of these tools in constructing the serialized 'fake' data.

Also, I didn't implement it, but I created options for turning on/off logging and also a severity enum for logging various levels of information.

There's some extension methods and also a factory for generating your fake model. It just helps when debugging and using stack trace rather than having everything in one method; especially with the rise of Visual Studio 2015's IntelliTrace/historic debugging and taking into consideration 'single responsibility' concept from 'S.O.L.I.D'.

I had some pretty complex architecture my side with all sorts of nested grid editors, custom plugins with properties that had custom data types etc and this takes care of all those scenarios; I was finding your logic a little troublesome so I though I'd contribute back and offer what I have done so you can update the pull request.

Thanks so much again for your great work. Attached is the zip containing all the new code.

Regards,
Matt Morrison.
[LeBlenderGridDataResolver.zip](https://github.com/Lecoati/LeBlender/files/440635/LeBlenderGridDataResolver.zip)

**Comment by hfloyd** [comment]
Thanks, Matt, for the cleanup and improvement work. I felt that what I had was functioning, but hacky (esp. the crazy string stuff)...

I look forward to testing it out in our next Courier project. :-)

I hope you've put in a pull request with your updated code.

Best wishes,
Heather

**Comment by alindgren** [comment]
@mattmorrisonsolidstudios - did you do a PR with your code, or is it just in the attached zip?

**Comment by mattmorrisonsolidstudios** [comment]
Hi,

There's already this pull request (Heather's) for 'Adding Courier Grid Data Resolver for LeBlender controls' and so I didn't want to create a duplicate. I don't think I can do a commit on this branch (her code) or can I? I thought that I have to fork the main and then add a new pull request which would kind of duplicate the work almost instead of adding an changeset to her code.

I'm new to github though, I've never made a fork or pull request using this service so naybe you guys can correct me if I'm wrong and point me in the right direction.

Warm regards,
Matt.

**Comment by mattmorrisonsolidstudios** [comment]
@alindgren yes it's just in the zip because of the above comments :) let me know if I can change that without duplicating too much

**Comment by mattmorrisonsolidstudios** [comment]
@hfloyd I forgot to mention, I also created a NuGet package for this which wraps the Courier 2 plugin and adds the data resolver class. I don't know what all the fuss is about with that because it was simple really.

**Comment by alindgren** [comment]
@Lecoati - it would be great if you could weigh  in on this...
@mattmorrisonsolidstudios - Is your Nuget available on nuget.org?

**Comment by hfloyd** [comment]
Hi @mattmorrisonsolidstudios , 

So, I was finally able to add your new version to an active UaaS project. I had some issues, though... 

The C#6 stuff caused compile issues in my project, so I made some modifications to get it to compile (turning the "$" back into "string.format()" and reverting the EditorAlias property code), but then once run, it didn't work very well - a lot of my content came across and was displaying like:
"\"\\\"\\\\\\\"MORE\\\\\\\"\\\"\"" 
(where MORE is the actual content...) So for now I have reverted back to my hacky version. I have attached the modified version of yours I had compiled. Perhaps you can see what went wrong...?

[LeBlenderGridDataResolver-new.zip](https://github.com/Lecoati/LeBlender/files/536961/LeBlenderGridDataResolver-new.zip)

**Comment by alindgren** [comment]
@hfloyd and @mattmorrisonsolidstudios - Thanks for sharing your code! I think it makes sense to publish this as it's own project. For one thing, not all LeBlender users will need to take a dependency on Courier. Also, it can be published without waiting for Lecoati. I'd love to get this in a nuget package!

**Comment by pdb-robert** [comment]
Hi, 
I´ve also run into this problem using LeBlender and UaaS and this seems to solve the problem. 
However, all values (strings) currently gets wrapped with an extra pair of \" and images should get its node id back from GUID. I´m not sure if ResolutionManager.Instance.ExtractingItem gets run on server, if this is what it´s suppose to do, and how i can verify this? 

Im using the source provided by the download link above, perhaps there are fixes in the NuGet package? 

Thanks!

**Comment by hfloyd** [comment]
@alindgren - 
Would it make sense to add this to Lee's already existing DataResolvers project rather than start another one?
https://github.com/leekelleher/umbraco-courier-dataresolvers

@pdb-robert : Try using my original code file: https://github.com/Lecoati/LeBlender/pull/30/files#diff-246a998efe632ca7c6f95a437a3d81f2

Just add it to your project and compile it along with your other code.

**Comment by alindgren** [comment]
@hfloyd - good question. I lean towards preferring a separate project with it's own Nuget but I guess bundling them together could be convenient and perhaps make it more discoverable. But either way, it will be nice to have it in a repo where we can track issues and make PRs.

**Comment by JJCLane** [comment]
Hey Heather! @hfloyd 

I've created a version based on @mattmorrisonsolidstudios contributions which fixes the issues you experienced regarding multiple serialization and also handles multiple properties perfectly. Works for us so let me know if there is anything that doesn't work for anyone.

https://gist.github.com/JJCLane/8020073f67525cce658893efd4b1b2ae 

Thanks.

**Comment by hfloyd** [comment]
Hi everyone,
So, Umbraco HQ has decided to take a more active role in managing extra DataResolvers, and have created their own repo here: https://github.com/umbraco/Umbraco.Courier.Contrib

I have a feeling that going forward, this will be considered the "definitive" collection, so I will be closing down this pull-request.

@JJCLane You might want to take a look at whether you can integrate your changes into the Umbraco repo.

Thanks for a great conversation.

**Pull request closed without merging**
