### PR TITLE
added public method HasProperty

### PR DESCRIPTION
**Pull request by ninjaonsafari**

### CODE REVIEW

**Comment by ninjaonsafari** [comment]
could you publish the new version to nuget?

**Comment by agiraud** [comment]
Yesterday @enricleon push a new version on nuget https://www.nuget.org/packages/Lecoati.LeBlender/1.0.8.1, your change has to be included into, could you check that?

**Comment by ninjaonsafari** [comment]
i've just updated to version 1.0.8.1 but i don't see my changes on the LeBelnderValue. Has @enricleon built the project before publishing?

**Comment by enricleon** [comment]
Tobias, It is my fault.

As I just changed the App_Plugins folder I didn't build the solution. I'm
going to publish again with your changes in a 1.0.8.2 version.



On 19 November 2015 at 10:27, Tobias Jason Lopez <notifications@github.com>
wrote:

> i've just updated to version 1.0.8.1 but i don't see my changes on the
> LeBelnderValue. Has @enricleon <https://github.com/enricleon> built the
> project before publishing?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Lecoati/LeBlender/pull/20#issuecomment-158000221>.
>



-- 
Enric.

**Comment by ninjaonsafari** [comment]
awesome thanks! #h5yr :grimacing:

**Pull request merged**
